spring.application.name=campus-room-booking

spring.datasource.url=jdbc:postgresql://localhost:5432/campus_room_booking
spring.datasource.username=campus
spring.datasource.password=campus
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
