CREATE TABLE IF NOT EXISTS rooms
(
    id BIGINT PRIMARY KEY,
    room_number  varchar(255) not null,
    building     varchar(255) not null,
    capacity     integer not null
);

CREATE TABLE IF NOT EXISTS bookings
(
	id BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	room_id  BIGINT NOT NULL,
	booked_by  varchar(255) NOT NULL,
	date DATE NOT NULL,
	start_time TIME NOT NULL,
	end_time   TIME NOT NULL,
	status    VARCHAR(255) NOT NULL,
    CONSTRAINT fk_bookings_room
    FOREIGN KEY (room_id) REFERENCES rooms(id)
);
